version: '2'
services:
  db-storage:
    image: takanamito/mysql-storage:latest
    volumes:
      - /var/lib/mysql
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes_from:
      - db-storage
  app:
    build:
      context: .
      dockerfile: dockerfiles/app/Dockerfile
    command: /bin/sh -c "rm -f ./tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/yakyu
    ports:
      - "3000:3000"
    depends_on:
      - db
